### ISSUE TITLE
[SP2]Prepare Database

### ISSUE THREAD

**Issue by pepea23** [gameushow/Gameplatform#23]
As a PO I want to see DB look like and how many of them will have 

Exit Caria 
- [x] Create migration
- [x] Create Model
- [x] TeachFriends
- [x] Need To Discuss how to design DB with Dev team

**Comment by pepea23** [comment]
<img width="319" alt="Screen Shot 2562-08-31 at 14 11 22" src="https://user-images.githubusercontent.com/32633442/64060593-2d5ee600-cbf9-11e9-8ec8-3ce2145e0084.png">

**Comment by RazerTotozz** [comment]
https://www.lucidchart.com/invitations/accept/8b49a2c0-082f-4b3b-adf6-6bc38da14291
